workflows:
  build_and_deploy:
    name: Build Android App
    scripts:
      - name: Grant execute permission to gradlew
        script: |
          chmod +x ./gradlew 
      - name: Build APK
        script: |
          ./gradlew assembleDebug
      - name: Build AAB
        script: |
          ./gradlew bundleRelease
    artifacts:
      - app/build/outputs/apk/debug/*.
      - app/build/outputs/bundle/release/*.aab